import redis
import json

# initializing the redis instance
r = redis.Redis(
    host='127.0.0.1',
    port=6379,
    decode_responses=True  # <-- this will ensure that binary data is decoded
)

sample_json = [{"id": "000168c9-a449-44da-8024-9cb947a07d31", "product_type": "Software", "name": "Simple Custom Reports for Jira", "domain": "simple-reports.com", "slug": "simple-custom-reports-for-jira", "description": "A powerful tool that allows you to create custom reports and gadgets for your team's kanban, scrum, or any other project management methodology with minimal configuration. With this app, you can instantly generate insightful and easy-to-use reports that give you a bird's eye view of your team's performance and progress, helping you make informed decisions and stay on top of your projects.\n\nOur app is designed to be user-friendly and intuitive, allowing you to quickly and easily configure the data you want to display and choose from a variety of chart types, including bar charts, pie charts, and line graphs. You can also customize the look and feel of your reports with a range of visual themes, making it easy to match your company's branding and style.\n\nWhether you're a project manager, team lead, or team member, our app for Jira is the perfect tool to help you stay organized, track progress, and drive results. Try it today and see how easy it is to get the insights you need to make your team more productive and successful."},
{"id": "0001747d-6236-45db-8f81-554c02f5968e", "product_type": "Software", "name": "Ampliz Healthcare Intelligence", "domain": "ampliz.com", "slug": "ampliz-healthcare-intelligence", "description": "Ampliz, the leading healthcare data provider, fulfills the data needs of Medical Device Manufacturing Companies, Pharmaceutical Companies, Healthcare Recruitment Firms, Medical Representatives, Diagnostic Centers, and all other healthcare-related subsidiaries."},
{"id": "000254c8-bfd5-4863-86a3-5f3ada87c725", "product_type": "Provider", "name": "MAKRAM SRL", "domain": "ibm.com", "slug": "makram-srl", "description": "MAKRAM SRL is a leading provider of IT services and solutions, specializing in software development, web design, and digital marketing. With a team of experienced professionals, we help businesses of all sizes achieve their goals and grow their online presence. Our services include custom software development, web design and development, mobile app development, e-commerce solutions, digital marketing, and more. Contact us today to learn how we can help you succeed online."},
{"id": "000287be-63c4-4d05-a960-7a3264936d3a", "product_type": "Software", "name": "Isogen", "domain": "hexagonppm.com", "slug": "isogen", "description": "Isogen is the world's leading solution for the total automation of piping isometric drawing production and is the Hexagon PPM standard system for drawing piping isometrics. Isogen is bundled with Intergraph Smart 3D, PDS, CADWorx, CAESAR II, and SmartPlant Spoolgen and SmartPlant Isometrics"},
{"id": "00032b56-f52f-4bd5-a677-7af7f2ff0c19", "product_type": "Software", "name": "GetJobsDone", "domain": "getjobsdone.nl", "slug": "getjobsdone", "description": "GetJobsDone is a platform with more than 10,000 ambitious young talents who carry out assignments for various clients. Working with GetJobsDone gives you the following:\n\n- Work based on output and get started immediately by means of an assignment agreement\n- Build a flexible pool of talented young professionals\n- Use the fresh perspective of young talents and get direct access to more than 10,000 employees of the future"},
{"id": "00036fb9-b9e3-4ef6-8c60-e4996f7c2ee0", "product_type": "Software", "name": "IMSWARE.GO", "domain": "imsware.de", "slug": "imsware-go", "description": "IMSWARE Technology offers complete solution packages from consultation to turn-key installation, having all the tools to fulfill your various legal obligations e.g. operator liability, risk analysis etc."},
{"id": "0003e281-09bc-42e3-abd6-435bad4e41e0", "product_type": "Software", "name": "Keeper", "domain": "keeper.app", "slug": "keeper", "description": "Keeper is an all-in-one app to streamline bookkeeping and client accounting services.\n \n\n Keeper sync directly to your client's QuickBooks file. This powers your custom-branded Client Portal, file reviews, management reporting, and workflow management.\n \n\n Stay on top of your work, get faster responses from your clients, and deliver reports they'll actually read. Try Keeper for free for 14 days, or schedule a customized demo to learn more."},
{"id": "00042459-9b33-404d-aa9b-7bc5d0712075", "product_type": "Software", "name": "EWCart", "domain": "ewcart.io", "slug": "ewcart", "description": "EWCart is the ideal eCommerce platform for you, offering you what you need for your business, plus your very own team of web developers to build and manage your site at no extra cost."},
{"id": "00057b36-f5ad-4d49-ad59-1dca5949f477", "product_type": "Software", "name": "OKAMSZ IT SOLUTIONS", "domain": "okamszitsolutions.in", "slug": "okamsz-it-solutions", "description": "OKAMSZ IT SOLUTIONS is a leading web application development company located in Trichy. Established by a group of well experienced software enthusiasts with great vision and knowledge in IT industry keeping digital marketing as focus. Our team has Indispensable knowledge in Mobile application development, Search Engine Optimization, eCommerce development, conversion optimization, custom application development, Search Engine Marketing and Info-graphics. Various software and tools are to build sites and applications for better results and ease of use. We solve complex problems at ease.We are Confined to provide best quality outputs adhering to customer\u2019s expectation, we always love to meet challenging customer requirements. The project team consists of full-time resources like analysts, designers, programmers, testers, etc., to work on projects."},
{"id": "0005d822-9d18-4579-8dfe-2bf048d3d6ff", "product_type": "Provider", "name": "Savvycom Software", "domain": "savvycomsoftware.com", "slug": "savvycom-software", "description": "Established in 2009, we\u2019ve consistently ranked among Vietnam\u2019s top 10 software development and IT outsourcing companies. Trusted by global enterprises, we now have offices in multiple countries, providing tailored solutions and IT team hiring services to address IT challenges and lower expenses."},
{
    "id": "0005f3b4-1b3b-4b3b-8b3b-3b3b3b3b3b3b",
    "product_type": "Arya",
    "name": "Arya Stark",
    "domain": "winterfell.com",
    "slug": "arya-stark",
    "description": "Arya Stark is the third child and second daughter of Lord Eddard Stark and his wife, Lady Catelyn Stark. After narrowly escaping the persecution of House Stark by House Lannister, Arya is trained as a Face"

},
{"id": "003f397a-912e-45b8-b562-df75cc898637", "product_type": "Software", "name": "Parafait", "domain": "semnox.com", "slug": "parafait", "description": "Semnox is a leading provider of customized holistic solutions for the global entertainment and leisure industry. Our clients include theme parks, adventure parks, water parks, family entertainment centres (FECs)/arcades, food courts/restaurants, health clubs and gyms. Our  specialities include innovative solutions (RFID/Barcode/QRCode/fingerprint-based) for ticketing and cashless operations, self-service kiosks, customer relationship management software, digital signage, and maintenance solutions. \n\nWe offer a single comprehensive system with 360\u00b0 CRM capabilities that allows operators to give their loyal customers the royal treatment they deserve through Loyalty, Membership & Rewards management, Promotions & Campaign Management and Business Analytics.\n\nOur products and solutions have been widely appreciated across the globe for consistently being at the cutting edge of innovation. We always strive to stay ahead of the latest technology trends and enhance our offerings to anticipate customer needs."},
{"id": "003f5dee-cf70-4be0-818c-cd0b28e2afed", "product_type": "Software", "name": "Express Menu Maker", "domain": "nchsoftware.com", "slug": "express-menu-maker", "description": "Start creating menus in three easy steps. Download Express Menu Restaurant Maker Software, enter and customize your menu items, and go ahead and print your menus. Create eye catching Restaurant, Cafe, or Bistro menus using this intuitive menu maker. Choose from over 20 templates including unique fonts, sizes and margins. This intuitive software allows you to add your own logo and print out your creations all in one process. Save your business time and money. Create, edit, print and save your menus with a user friendly interface. Features: Craft the perfect menu using the intuitive interface 20+ Professional Templates Customize your fonts, sizes and margins Upload your own logo Print in all popular paper sizes Easily create and save your food and drink options Add descriptions, notes and optional extras Business and Enterprise Editions are available from NCH Software. About NCH Software: NCH Software is a leader in audio, video, music, mp3, cd, dvd, telephony, dictation, transcription, business, and computer utility software for Windows, Palm, Pocket PC and Mac OS X."},
{"id": "003f876e-0f87-48a0-b7e4-ab0f748bd8f6", "product_type": "Software", "name": "IsoPlan", "domain": "isovist.co.nz", "slug": "isoplan", "description":"Not available"},
{"id": "003fe4b4-3125-4692-90c3-58a43a0b16e6", "product_type": "Provider", "name": "Think Strategy", "domain": "thinkstrategy.com", "slug": "think-strategy", "description": "Think Strategy is an inbound and outbound growth marketing agency that helps business-to-business (B2B) companies generate leads and sales online."},
{"id": "00405fbf-3dbe-456e-acef-afc60c5bd514", "product_type": "Provider", "name": "Nordicorm", "domain": "nordicom.se", "slug": "nordicorm", "description": "Nordicom is a center for services regarding better customer relations and we are helping nordic brands to excel and strengthen their market position by creating a more loyal customer base by outsourcing of customer service. We ensure high quality by meeting your customer in every channel offering a 360\u00b0 service, focus on education, agent-satisfaction and continual coaching. Nordicom - It's solved.\n\nServices: Outsourcing customer service, Outsourcing customer service, Recruitment, Staffing, B2B & B2C sales\nTj\u00e4nster: Outsourcing kundservice, Outsourcing kundtj\u00e4nst, Rekrytering, Bemanning, B2B & B2C f\u00f6rs\u00e4ljning"},
{"id": "0040c2f1-2d40-461b-91c7-79c2fb02cbc6", "product_type": "Provider", "name": "Skyview", "domain": "skyviewads.com", "slug": "skyview", "description": "Skyview is one of the best website designing and website development companies in Lucknow. If you want to have your website or web applications designed and developed professionally, Skyview Solutions is the only place you\u2019ll ever need to go."},
{"id": "0040d853-d341-47cd-843f-7bf4c7518413", "product_type": "Software", "name": "Hardened Microsoft Windows Server 2012 R2", "domain":"Not available", "slug": "hardened-microsoft-windows-server-2012-r2", "description": "Not available"},
{"id": "0040dec3-8dc5-4a08-a85f-fb8ed5522a03", "product_type": "Provider", "name": "Switch Data Centers", "domain":"Not available", "slug": "switch-data-centers", "description":"Not available"},
{"id": "0040e3e0-baad-49ed-b36c-cc8598062edf", "product_type": "Software", "name": "Highway 905 Transportation Management System", "domain": "highway905.com", "slug": "highway-905-transportation-management-system", "description": "multi-fold freight cost reductions to increased customer satisfactions with a more efficient end-to-end delivery management setup with our Highway 905 Transportation Management System and Highway 905 Shipment Tracking System or pick and choose your products from our customizable plug-ins for your exact business needs"},
{"id": "00416300-681c-4040-ac51-7eeb01321d95", "product_type": "Software", "name": "CRMBOOST", "domain": "crmboost.com", "slug": "crmboost", "description": "eep your business within sight with our extensive intelligence tools."},
{"id": "00416eaa-4164-4634-935d-c39bd1af2dd4", "product_type": "Software", "name": "AppColl", "domain": "appcoll.com", "slug": "appcoll", "description": "AppColl Prosecution Manager is a cloud-based IP management product designed to significantly increase productivity while reducing both the costs and risks of running a small patent firm or corporate IP group."},
{"id": "00419a64-18d5-466c-b1b5-3c5de9160a78", "product_type": "Software", "name": "schnaq", "domain": "schnaq.com", "slug": "schnaq", "description": "Fully understand your audience anytime with schnaq. Activate everyone in your workshop, webinar or any other event and demonstrate your expertise as a speaker with the knowledge cards. Use schnaq online, offline and in hybrid settings."},
{"id": "0041f6ba-ed64-4537-9f5c-5e59056d324d", "product_type": "Provider", "name": "The Writing Services", "domain": "thewritingservices.com", "slug": "the-writing-services", "description": "The Writing Services is the world\u2019s No 1 online research & writing services provider company that has been providing writing services in India, the United Kingdom, Australia, the United States, Canada, and more than 25+ countries at a pocket-friendly cost to students, small businesses, education startups, online learning platforms since 2012.\n\nWe at The Writing Services provide Academic & Content Writing Services globally. We hereby propose to collaborate with your esteemed organization. \n\nWe provide Assignment Help to students in the UK, USA, Canada & Australia at the graduate and postgraduate levels. We have a team of professional Academic Writers who are talented, experienced, and dedicated. We provide impeccable quality, low-cost, writing solutions to our clients. \n\nYou may go through our sample works or get a sample work done from us to assess the quality of our work. We intend to build trust for a strong long-term relationship.\n\nBefore I tell you more about us, let me first walk you through our services.\n \nOur services primarily include :\n\u2022     Academic Essay writing\n\u2022     Report writing\n\u2022     Academic Research paper\n\u2022     Thesis\n\u2022     Dissertations\n\u2022     Case Study Analysis\n\u2022     PowerPoint Presentation\n\u2022     Online Class & Quiz\n\u2022     Literature Review\n\u2022     Personal Statements & SOP  \n\u2022     CV and Cover letter\n\n\nWhy Choose The Writing Services Company For Your Businesses and Assignments?\nOutstanding Quality-We ensures that the work is original & genuine. It is also double-checked &\n   proofread before it lands in the client\u2019s Inbox.\n\u2022 Timely Delivery\u2013We deliver the work well within agreed deadlines.\n\u2022 Plagiarism-free Content\u2013We also provide a free Turnitin Report.\n\u2022 Unlimited Revisions & Reworks till the client is fairly satisfied.\n\nWhen you feel free then you can contact me at \n\u2022\tEmail Id \u2013 admin@thewritingservices.com\n\u2022\tNumber for India \u2013 9351947088 / 8696032203\n\u2022\tNumber for out of India \u2013  +1 (424) 999-8118\n\u2022\tSkype id \u2013 https://join.skype.com/invite/WfJekIUavG5g"},
{"id": "00421fb0-c01d-430e-a14f-07ee94dc5360", "product_type": "Software", "name": "IdeaRoom", "domain": "idearoominc.com", "slug": "idearoom", "description": "IdeaRoom is a product configuration software designed to offer a complete online sales solution for build-to-order products."},
{"id": "0042ee43-31a3-433c-8235-b7cf226ce9a8", "product_type": "Software", "name": "AgriChain", "domain": "agrichain.com", "slug": "agrichain", "description": "AgriChain brings together all stakeholders in the agricultural supply chain, allowing them make better-informed decisions, eliminate unnecessary paperwork and dockets, reduce supply chain inefficiency and risk, open markets and increase their bottom line, all on one easy-to-use platform."},
{"id": "00433842-84aa-4507-886c-c6efbdc555a5", "product_type": "Software", "name": "Vimsy", "domain": "vimsy.co", "slug": "vimsy", "description": "Bring videos from Youtube, Vimeo and Wistia together to create your own online video channel."},
{"id": "0043b63c-1c37-4d51-8bac-4b41133653af", "product_type": "Provider", "name": "Work 2-gether", "domain": "work2gether.com.br", "slug": "2-plan-work-2-gether", "description": "Coworking is a new way of thinking about the work environment. Following the trends of freelancing and start-ups, coworkers bring together thousands of people daily in order to work in an inspiring environment."},
{"id": "0043df01-2d86-45f6-ba43-7de3f726384c", "product_type": "Software", "name": "HighSide Multi-Factor Authentication", "domain": "highside.io", "slug": "highside-multi-factor-authentication", "description": "SecureAccess fulfills the promise that authentication security should enable users, not confound them. Leverage HighSide\u2019s private root of trust to broker access xto internal systems and 3rd party cloud applications, all with the push of a user's index finger."},
{"id": "00441d33-57dd-4f77-a934-5f5e51f92319", "product_type": "Software", "name": "TrueQuant Imaging Software", "domain": "perkinelmer.com", "slug": "truequant-imaging-software", "description": "TrueQuant software makes 3D fluorescence tomography easy with streamlined tools for data management, automatic reconstruction, and high throughput data analysis."},
{"id": "00448565-be8d-42a9-b5d7-a11b722615e4", "product_type": "Provider", "name": "Cisco IronPort", "domain": "ironportstore.com", "slug": "cisco-ironport", "description": "The Cisco-IronPort S-Series web security appliance is the industry's first and only secure web gateway to combine next generation Web Usage Controls, reputation filtering, malware filtering and data security on a single platform to address these risks."},
{"id": "0044ab75-46de-43dc-9ec5-1965286d5a45", "product_type": "Provider", "name": "Reivernet", "domain": "reivernet.com", "slug": "reivernet", "description": "Reivernet is a premium provider of guest internet solutions to the hospitality industry.  Since 2001 we have designed, built, configured and managed hotel networks for all the major global hotel brands. We operate over 500+ hotels across 34-countries, and are the only vendor to be endorsed by all five of the global hotel chains."},
{"id": "0044feb8-6223-414e-b9a0-b79424145cec", "product_type": "Provider", "name": "NS Solutions", "domain": "nipponsteel.com", "slug": "ns-solutions", "description": "A leading system integrator and solution provider in Japanese manufacturing industry."},
{"id": "00450f00-7318-4591-802a-e79d9ef9ca8e", "product_type": "Software", "name": "LAMP Stack - Ubuntu 20.04- Dev Ready", "domain": "amazon.com", "slug": "lamp-stack-ubuntu-20-04-dev-ready", "description":"Not available"},
{"id": "00457f17-efd4-434d-a814-65a819e7f7e8", "product_type": "Software", "name": "Talega Systems", "domain": "talegasystems.com", "slug": "talega-systems", "description":"Not available"},
{"id": "0045cb9f-6cb0-4f72-a72e-28410d3e16d1", "product_type": "Software", "name": "Lean Testing", "domain": "leantesting.com", "slug": "lean-testing", "description": "With the Lean Testing browser extension, you can take screenshots, annotate them, and report bugs without leaving the page you're on."},
{"id": "0045d1b4-1b3b-4b3b-8b3b-3b3b3b3b3b3b", "product_type": "Arya", "name": "Arya Stark", "domain": "winterfell.com", "slug": "arya-stark", "description": "Arya Stark is the third child and second daughter of Lord Eddard Stark and his wife, Lady Catelyn Stark. After narrowly escaping the persecution of House Stark by House Lannister, Arya is trained as a Face"},
{"id": "0045f3b4-1b3b-4b3b-8b3b-3b3b3b3b3b3b", "product_type": "Arya", "name": "Arya Stark", "domain": "winterfell.com", "slug": "arya-stark", "description": "Arya Stark is the third child and second daughter of Lord Eddard Stark and his wife, Lady Catelyn Stark. After narrowly escaping the persecution of House Stark by House Lannister, Arya is trained as a Face"},]


for json_message in sample_json:
    # json_message = input("Enter the JSON message you want to send to soldiers: ")
    try:
        r.publish("army-camp-1", json.dumps(json_message))
        print(f"Published message: {json_message}")
    except json.JSONDecodeError:
        print("Invalid JSON format. Please try again.")